# Generated by Django 4.0 on 2022-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=16, verbose_name='Color')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('sub_score', models.IntegerField(default=0, verbose_name='Sub score')),
            ],
        ),
    ]
