# Generated by Django 4.0 on 2022-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
